version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "cypress"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Azanul/Next-Watch"
