// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attr struct {
	Name       string `json:"name"`
	Importance int    `json:"importance"`
}

type InputAttr struct {
	Name       string `json:"name"`
	Importance int    `json:"importance"`
}

type Movie struct {
	ID      string  `json:"_id"`
	Name    string  `json:"name"`
	Poster  string  `json:"poster"`
	Actors  []*Attr `json:"actors"`
	Watched bool    `json:"watched"`
}

type NewMovie struct {
	Name    string       `json:"name"`
	Poster  string       `json:"poster"`
	Actors  []*InputAttr `json:"actors"`
	Watched bool         `json:"watched"`
}
